# Generated by Django 5.2.7 on 2026-01-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='is_used',
        ),
        migrations.AlterField(
            model_name='otp',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
